Algoritmo "ExemploImprimaRepitaInterrompa1a10"
// Lógica de Programação
// Professor: Marcos Monteiro
// Descrição: Repita Interrompa
// Autora: Barbara Barbosa
// Data: 29/10/2022
Var
   j: inteiro

Inicio
      escreval("Imprima de 10 a 1(Repita até):")
      j <- 1
      repita
      escreval(j)
      j <- j+1
      se j=5 entao
      interrompa
      
      fimse
      
      ate j > 10
      escreval("Executando após um Interrompa J= ", j)

Fimalgoritmo