Algoritmo "ExemploTabuada"
// Lógica de Programação
// Professor: Marcos Monteiro
// Descrição: Enquanto
// Autora: Barbara Barbosa
// Data: 28/10/2022
Var
   j, numero: inteiro

Inicio
      escreva("Digite o número para tabuada: ")
      leia(numero)
      j <- 1
      enquanto j < 11 faca
      escreval(numero, " x ", j, " = ", (numero*j))
      j <- j+1

      fimenquanto
      
      escreval("Continuando após o enquanto.")

Fimalgoritmo