Algoritmo "ExercicioImprimaMultiplo3"
// Lógica de Programação
// Professor: Marcos Monteiro
// Descrição: Para
// Autora: Barbara Barbosa
// Data: 28/10/2022

Var
   j, numero1, numero2: inteiro;

Inicio
   escreval("Imprimindo múltiplos de 3 entre dois números. Escolha: ")
   leia(numero1, numero2)
   para j de numero1 ate numero2 faca
      se (j%3) = 0 entao
      escreval (j)

   fimse
   fimpara

Fimalgoritmo